CREATE TABLE
    "users" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email TEXT NOT NULL UNIQUE,
        hash TEXT NOT NULL,
        salt TEXT NOT NULL,
        email_verified BOOLEAN NOT NULL,
        email_verified_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
        CONSTRAINT users_email_unique UNIQUE (email),
    );

-- TODO: per recipient messages
-- CREATE TABLE
--     "messages" (
--         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--         content TEXT NOT NULL,
--         created_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
--         updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
--     );