name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build-web:
    runs-on: ubicloud-standard-2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: ubicloud/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: ubicloud/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: cd web && pnpm install

      - name: Build web
        run: cd web && pnpm build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: web/dist
          if-no-files-found: error

  cargo-build:
    runs-on: ubicloud-standard-2
    needs: build-web
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: web/dist

      - name: Set up Rust (nightly)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Cache dependencies
        uses: ubicloud/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache sccache folder
        uses: ubicloud/cache@v4
        with:
          path: ~/.cache/sccache
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/*.rs', '**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-sccache-

      - name: Release Build
        run: |
          cargo build --release --bin web-server
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Upload final binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: target/release/web-server
          if-no-files-found: error

  build-image-and-upload:
    runs-on: ubicloud-standard-2
    needs: cargo-build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to github registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download server binary
        uses: actions/download-artifact@v4
        with:
          name: server
          path: server-bin

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: web/dist

      - name: Build and push Docker image
        run: docker buildx build --push -t ghcr.io/${{ github.repository }}/api:latest -f scripts/dockerfiles/web.Dockerfile .
